name: Build and Test

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-18.04
    container: racket/racket-ci:latest

    strategy:
      fail-fast: false
      matrix:
        vm: ['regular', 'CS']

    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v0.10
      with:
        architecture: 'x64'
        distribution: 'minimal'
        variant: ${{ matrix.vm }}
        version: 'current'
    - name: Install and setup
      run: |
        raco pkg install --auto compiler-lib
        raco pkg install --auto -i --no-setup --skip-installed racket-test
        raco setup --pkgs racket-test
        raco pkg install --auto -i --no-setup --skip-installed compatibility-test
        racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
        echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
        raco pkg config catalogs >> catalog-config.txt
        raco pkg config --set catalogs `cat catalog-config.txt`
        raco pkg update -i --auto --no-setup compatibility-lib/ compatibility-test/
        raco setup --pkgs compatibility-lib compatibility-test
    - name: Run tests
      run: |
        raco test -e -l tests/mzlib/test
        raco test -e -l tests/racket/package
        raco test -e -l tests/racket/package-arrows
